#!/bin/node
var daemon = require("daemonize2").setup({
    main: "sched.js",
    name: "dummy_optimizer",
    pidfile: "dummy.pid"
});

switch (process.argv[2]) {

    case "start":
		
        daemon.start();
        break;

    case "stop":
        daemon.stop();
        break;
        
    case "status":
		var pid = daemon.status();
        if (pid>0)
          console.log("Dummy Scheduler is running with pid: " + pid)
        else
		  console.log("Dummy Scheduler not running.")
        break;

    default:
        console.log("Usage: [start|stop]");
}
